insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Mr');

insert into COURSE_MATERIAL (url, course_id) values ('https://gnu.org/aliquam.html', 1);
insert into COURSE_MATERIAL (url, course_id) values ('http://bbc.co.uk/id.aspx', 2);
insert into COURSE_MATERIAL (url, course_id) values ('http://sun.com/justo/sit/amet.html', 3);
insert into COURSE_MATERIAL (url, course_id) values ('http://cnbc.com/dignissim/vestibulum/vestibulum/ante/ipsum.aspx', 4);
insert into COURSE_MATERIAL (url, course_id) values ('https://51.la/lobortis.aspx', 5);
insert into COURSE_MATERIAL (url, course_id) values ('https://4shared.com/odio/elementum.jpg', 6);
insert into COURSE_MATERIAL (url, course_id) values ('https://slate.com/tortor.js', 7);
insert into COURSE_MATERIAL (url, course_id) values ('https://goo.gl/tincidunt.png', 8);
insert into COURSE_MATERIAL (url, course_id) values ('https://china.com.cn/dapibus/duis/at/velit.json', 9);
insert into COURSE_MATERIAL (url, course_id) values ('http://google.de/rhoncus/aliquam/lacus/morbi/quis/tortor/id.png', 10);
insert into COURSE_MATERIAL (url, course_id) values ('https://51.la/est/risus/auctor.png', 11);
insert into COURSE_MATERIAL (url, course_id) values ('https://gravatar.com/aenean/lectus/pellentesque/eget.xml', 12);
insert into COURSE_MATERIAL (url, course_id) values ('http://miitbeian.gov.cn/vel/ipsum/praesent/blandit/lacinia/erat/vestibulum.html', 13);
insert into COURSE_MATERIAL (url, course_id) values ('https://ca.gov/rhoncus/dui/vel/sem/sed/sagittis/nam.jpg', 14);
insert into COURSE_MATERIAL (url, course_id) values ('https://census.gov/nulla.js', 15);
insert into COURSE_MATERIAL (url, course_id) values ('https://google.co.uk/libero/ut/massa/volutpat/convallis/morbi.json', 16);
insert into COURSE_MATERIAL (url, course_id) values ('http://npr.org/duis/bibendum/felis.aspx', 17);
insert into COURSE_MATERIAL (url, course_id) values ('http://jigsy.com/eu/nibh/quisque/id.xml', 18);
insert into COURSE_MATERIAL (url, course_id) values ('http://paypal.com/curabitur/convallis/duis.jsp', 19);
insert into COURSE_MATERIAL (url, course_id) values ('https://amazon.co.uk/ligula/nec/sem/duis/aliquam.aspx', 20);
insert into COURSE_MATERIAL (url, course_id) values ('https://slashdot.org/in.xml', 21);
insert into COURSE_MATERIAL (url, course_id) values ('https://123-reg.co.uk/varius/ut.html', 22);
insert into COURSE_MATERIAL (url, course_id) values ('https://t-online.de/donec.aspx', 23);
insert into COURSE_MATERIAL (url, course_id) values ('https://yahoo.co.jp/odio/justo.xml', 24);
insert into COURSE_MATERIAL (url, course_id) values ('http://jigsy.com/mauris/ullamcorper/purus/sit.png', 25);
insert into COURSE_MATERIAL (url, course_id) values ('https://sciencedaily.com/tempus.jsp', 26);
insert into COURSE_MATERIAL (url, course_id) values ('https://altervista.org/pede.js', 27);
insert into COURSE_MATERIAL (url, course_id) values ('https://umn.edu/mauris/enim/leo/rhoncus/sed/vestibulum.jsp', 28);
insert into COURSE_MATERIAL (url, course_id) values ('https://storify.com/at/diam/nam.jsp', 29);
insert into COURSE_MATERIAL (url, course_id) values ('https://phoca.cz/hac/habitasse/platea/dictumst/etiam/faucibus/cursus.aspx', 30);