INSERT INTO COURSE (ID,TITLE ) VALUES (001,'Curso 1');
INSERT INTO COURSE (ID,TITLE ) VALUES (002,'Curso 2');
INSERT INTO COURSE (ID,TITLE ) VALUES (003,'Curso 3');

INSERT INTO COURSE_MATERIAL (ID,URL,COURSE_ID) VALUES (0001, 'http://net-balmes-JPARelaciones-rrufo.net', 001);
INSERT INTO COURSE_MATERIAL (ID,URL,COURSE_ID) VALUES (0002, 'http://net-balmes-JPARelaciones-rrufo.net', 002);
INSERT INTO COURSE_MATERIAL (ID,URL,COURSE_ID) VALUES (0003, 'http://net-balmes-JPARelaciones-rrufo.net', 003);
